name: Lint with Flake8

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # Specify your Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pyyaml  # Install Flake8 and PyYAML
      - name: Run Flake8
        run: python run_flake8.py
